// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package slurm

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "slurm", asset.ModuleFieldsPri, AssetSlurm); err != nil {
		panic(err)
	}
}

// AssetSlurm returns asset data.
// This is the base64 encoded zlib format compressed contents of module/slurm.
func AssetSlurm() string {
	return "eJzEj01uwyAUhPecYuS9L8Ciu56jwmZaUYNB/Kj17SubJrEdlF2Ub8d74nszPSYuEsmW6ASQTbaU6LZ3J4BIS5UoMTArAWimMZqQjZ8l3gSA+hfO62IpgE9Dq5PcVj1m5XjTr+QlUOIr+hL+Jw3nUbNXffvhYwzlOm8JV87BLzSPVe7V5xD7IPxVLmyN99QwE5cfH/Vp9+D0ynsV1qPN3o7uWb2P6hf2/gsAAP//8z6o8w=="
}
