// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package slurm

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "slurm", asset.ModuleFieldsPri, AssetSlurm); err != nil {
		panic(err)
	}
}

// AssetSlurm returns asset data.
// This is the base64 encoded zlib format compressed contents of module/slurm.
func AssetSlurm() string {
	return "eJzslUGTojAQhe/8ilfe3R/AYS+7l93TXjxvBdJqNKGZdFIO8+unguggBqe0nNv0jQTe916ahiX21JUQG70rgGCCpRKL/npRAJ4sKaESG1UAmqT2pg2GmxI/CwDHJ+FYR0uouQnKNAJHwZtasGYPR459B9Vo1G1EFLUh8Bo7rqQA1oaslrIXW6JRjj7spApdm/CeYzusZFxcyoyldlz9r9t4Xs8JpjoHrSio0XoWdqxB+jq1EuHaqEAaBxO2+PVvdRn7x0hnanxqPgr5i81Tgj11B/Z6snfDb6qVkE/aVx53XM1ZMFPGkW+52dwH/8sV/vzOYuo2xmBsFqQ5VpbuQ/VHHow1byrdMhz8LFoon/Fh9Kjbc1BPL89kShm2npQW+BQ5OwiO3FcNgiP3+SAMn4LvWbg5CxKofV7KBLpSPKEcub4ZTwqV6e8cdu7tfwCqXo2LDspxbELCDjbSzyc5eA8AAP//kGjIIw=="
}
