// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package slurm

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "slurm", asset.ModuleFieldsPri, AssetSlurm); err != nil {
		panic(err)
	}
}

// AssetSlurm returns asset data.
// This is the base64 encoded zlib format compressed contents of module/slurm.
func AssetSlurm() string {
	return "eJzslbFy8jAQhHs/xQ49/wO4+JukSao01BnZOkAg+RydNMR5+oyMScDIZGBIl+ss2fvt6nz2HFvqSoiN3hVAMMFSiVl/PSsAT5aUUImKgioATVJ70wbDTYn/BYD9s3CsoyXU3ARlGoGj4E0tWLKHI8e+g2o06jYiiloReIkNV1IAS0NWS9mLzdEoR9+GUoWupRIrz7EdVjIuTmWOpTZcvdZt/FrPCaYaRz1UFravQfo8tRLh2qhAGjsT1nh4WZzG/nekMzY+Nh+F/MnmIcGWuh17Pdq74DfVQsgn7TOPG66mLJgxY8+33Kyugz9zhafHLKZuYwzGZkGaY2XpOlR/5MFY86HSLcPBT6KF8hlvRh91ewrq6e2eTCnD2pPSAp8iZwfBkfutQXDkfh6E4VPwNwsXZ0ECtfdLmUBnigeUI9c3406hMv2dwk69/TdA1btx0UE5jk1I2MFG+vkkB58BAAD//z6TyPc="
}
